### ISSUE TITLE
How to fix the down of server: https://danctnix.arikawa-hi.me/rootfs/archarm-on-mobile?

### ISSUE THREAD

**Issue by ghost** [dreemurrs-embedded/archarm-mobile-fde-installer#24]
Hello I really would like to reinstall arch with FDE, but I need a workaround for the service https://danctnix.arikawa-hi.me/rootfs/archarm-on-mobile that is down for a few months.

**Comment by Danct12** [comment]
Duplicate of #23

**Comment by ghost** [comment]
Is there a work-around for this problem?
