### ISSUE TITLE
Error: Checksum does not match

### ISSUE THREAD

**Issue by ghost** [dreemurrs-embedded/archarm-mobile-fde-installer#4]
After the image get's downloaded:

curl: option --progress-meter: is unknown
curl: try 'curl --..............................'
sha512sum: 'standard input': no properly formatted SHA512 checksum lines found
ERROR: Checksum does not match. Aborting

I might be missing something obvious, but can't get passed the checksum check

**Comment by ghost** [comment]
mm, might just be the options for curl have updated. New options for curl for progress meter is "progress-bar". Will quickly edit the script with this correction and see if it works.

**Comment by ghost** [comment]
FIXED!

Options for curl for me resulted in changing --progress-meter to --progress-bar, or just remove it lol. 

Sorry for the false alarm. Cheers

**Comment by Danct12** [comment]
Can you please give me the output of `curl --version`?

**Comment by ghost** [comment]
`curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL`


Seems like an older version, current stable is at 7.75? At some point it changed. I was using pureOS inside a vbox for this as I didn't have another system. Supposed I could have flashed the sdcard with a regular relase of arch or something, boot from sd and then run it through that to flash the emmc with this installer lol

EDIT: There was one other issue I had yesterday but ended up working at the end, so I didn't post it. During the stage where the images are finished downloading and it starts preparing the drives for partitioning/wiping, I got the error numerous times either the drive was in use, drive had existing partitions, or drive was "uncompatible" and then it aborts (I was selecting the pinephones emmc directly - which did have mobian installed on it). I assumed that it would still work and it would just ignore and erase and re-partition anyways, but kept throwing up a combination of those errors. So I tried using gparted just to erase the emmc completely (to unallocated memory), tried the installer and got drive is "uncompatible". Then ended up using gparted and created a 'skeleton" by creating a boot partition, and an empty f2fs partition - almost like a template for it lol. Then it finally worked and installed it - any ideas on this? 

All in all though, once I got it working, by far my favorite distro so far on the pinephone :)
