### ISSUE TITLE
Progress Meter for curl command

### ISSUE THREAD

**Issue by KnightWhoSaysNeeeowWumPing** [dreemurrs-embedded/archarm-mobile-fde-installer#5]
I came across the issue that at least my version of curl (7.64.0 on a current Debian box, as well as 7.75.0 on a Manjaro system) did not support the `--progress-meter` parameter. Therefore the checksum verification fails in the following manner:

```
curl: option --progress-meter: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
sha512sum: 'standard input': no properly formatted SHA512 checksum lines found
ERROR: Checksum does not match. Aborting.
```

Chaning the parameter to `--progress-bar` in [this line](https://github.com/dreemurrs-embedded/archarm-mobile-fde-installer/blob/master/installer.sh#L131) did the trick.

I'm just curious if this was intentional since it seems to be working fine for others.

**Comment by failpyre** [comment]
I had the same issue. PR submitted: https://github.com/dreemurrs-embedded/archarm-mobile-fde-installer/pull/7
